# This is a basic workflow to help you get started with Actions

name: CI Pipeline with Maven, Spotbugs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
      
  PMD:

   runs-on: ubuntu-latest
   
   needs: build

   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
         cache: maven
     - name: PMD with Maven
       run: mvn pmd:check
       
  spotbugs:
  
   permissions: write-all
  
   runs-on: ubuntu-latest
   
   needs: build

   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
         cache: maven
     - name: Spotbugs with Maven
       run: mvn spotbugs:check 
     - name: Publish SpotBugs Report
       if: always()
       uses: jwgmeligmeyling/spotbugs-github-action@b8e2c3523acb34c87f14e18cbcd2d87db8c8584e
       with:
          name: SpotBugs Report JDK ${{ matrix.java }}
          path: 'reports/spotbugs/*.xml'
   
   
      
